version: "3.8"

services:
  simulator:
    image: ros2
    container_name: ros2-assessment
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./sawyer_gazebo_blocks_puzzle:/root/ros_ws/src/sawyer_simulator/sawyer_gazebo_blocks_puzzle
    network_mode: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t